# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 16:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('letter', models.CharField(choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D')], max_length=1)),
                ('marks', models.PositiveIntegerField()),
                ('text_field', models.TextField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'class_levels',
            },
        ),
        migrations.CreateModel(
            name='CompletedTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Answer')),
            ],
            options={
                'db_table': 'completed_tests',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('date_available', models.DateTimeField(default=django.utils.timezone.now)),
                ('hours', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1 Hour'), (2, b'2 Hours'), (3, b'3 Hours')], null=True)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, choices=[(15, b'15 Minutes'), (30, b'30 Minutes'), (45, b'45 Minutes')], null=True)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=56)),
                ('excel_file', models.FileField(upload_to=b'files/uploads')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='FeeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=50)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel')),
            ],
            options={
                'db_table': 'fee_elements',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel')),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.FeeElement')),
            ],
            options={
                'db_table': 'fee_structure',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=b'galary')),
            ],
            options={
                'db_table': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'parents',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('number', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[(b'E', b'Easy'), (b'M', b'Medium'), (b'H', b'Hard')], max_length=1, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('out_off', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('mission', models.TextField(max_length=200)),
                ('vision', models.TextField(max_length=200)),
                ('code', models.CharField(max_length=8)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('country', models.CharField(default=b'Kenya', max_length=50)),
                ('county', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('gender_type', models.CharField(choices=[(b'B', b"Boy's School"), (b'G', b"Girl's School"), (b'M', b'Mixed')], max_length=1)),
                ('private', models.CharField(choices=[(b'Private', b'Private'), (b'Public', b'Public')], max_length=7)),
                ('approved', models.BooleanField(default=False)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('kindergarten', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_students', models.PositiveIntegerField(blank=True, null=True)),
                ('app_level', models.CharField(choices=[(b'G', b'Gold'), (b'S', b'Silver'), (b'T', b'Titanium')], max_length=1)),
                ('payed_status', models.BooleanField()),
                ('directors', models.ManyToManyField(blank=True, to='easy.Director')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=20)),
                ('class_level', models.ManyToManyField(to='easy.ClassLevel')),
            ],
            options={
                'db_table': 'school_levels',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'streams',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reg_number', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to=b'files/uploads')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Stream')),
            ],
            options={
                'db_table': 'student_uploads',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('class_level', models.ForeignKey(db_column=b'level_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('phone', models.CharField(max_length=13, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[(b'HM', b'Head Teacher'), (b'DP', b'Deputy teacher'), (b'SM', b'Senior Master'), (b'CT', b'Class Teacher'), (b'EH', b'Examination Head'), (b'AA', b'Academic Affairs'), (b'HOS', b'Head of Sciences'), (b'HOH', b'Head of Humanities'), (b'HOL', b'Head of Languages'), (b'HOM', b'Head of Mathematics')], max_length=4, null=True)),
                ('classes', models.ManyToManyField(blank=True, to='easy.Stream')),
                ('school', models.ForeignKey(blank=True, db_column=b'school_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='easy.School')),
                ('subjects', models.ManyToManyField(blank=True, to='easy.Subject')),
            ],
            options={
                'db_table': 'teachers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('class_level', models.ForeignKey(db_column=b'level_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Subject')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easy.Question')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('choices', models.ManyToManyField(blank=True, to='easy.Answer')),
            ],
            options={
                'db_table': 'multiple_choices',
            },
            bases=('easy.question',),
        ),
        migrations.CreateModel(
            name='ResultObjects',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='easy.Exam')),
                ('average_marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'averages',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.ManyToManyField(blank=True, to='easy.Topic'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='easy.Parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Stream'),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Teacher'),
        ),
        migrations.AddField(
            model_name='stream',
            name='level_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel'),
        ),
        migrations.AddField(
            model_name='school',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skull', to='easy.Teacher'),
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.SchoolLevel'),
        ),
        migrations.AddField(
            model_name='school',
            name='stream',
            field=models.ManyToManyField(blank=True, to='easy.Stream'),
        ),
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='results',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Exam'),
        ),
        migrations.AddField(
            model_name='results',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Student'),
        ),
        migrations.AddField(
            model_name='question',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Topic'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='feeelement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ClassLevel'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='exam',
            name='stream',
            field=models.ManyToManyField(blank=True, to='easy.Stream'),
        ),
        migrations.AddField(
            model_name='exam',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Teacher'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='sponsors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Sponsor'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(to='easy.EventOrganizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='completedtests',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Student'),
        ),
        migrations.AddField(
            model_name='completedtests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Exam'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AddField(
            model_name='resultobjects',
            name='results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Results'),
        ),
        migrations.AddField(
            model_name='resultobjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Subject'),
        ),
        migrations.AddField(
            model_name='resultobjects',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_ans',
            field=models.ManyToManyField(blank=True, to='easy.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='completedtests',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.MultipleChoiceQuestion'),
        ),
    ]
